### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered while setting image for predictor

### ISSUE THREAD

**Issue by MaxTeselkin** [facebookresearch/segment-anything#490]
Hi! I am trying to use Segment Anything, but I constantly get RuntimeError: CUDA error: an illegal memory access was encountered.

**Comment by mishra077** [comment]
Which pytorch version are you using?

**Comment by MaxTeselkin** [comment]
@mishra077 I am using pytorch 1.12.1

**Comment by kalpa61** [comment]
@MaxTeselkin Hello, have you solved this problem

**Comment by Yo-AvA** [comment]
@MaxTeselkin  hi! Have you found any solutions?

**Comment by NormXU** [comment]
I came across the same issue with `SamAutomaticMaskGenerator` and resolved it by decreasubf the `points_per_batch`.
